version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - "8090:80"
    networks:
      - web-net

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    networks:
      - web-net

networks:
  web-net:
    driver: bridge